stages:
  download_sqlite:
    cmd: Rscript R/build.R
    deps:
      - R/build.R
    outs:
      - data/chembl_30.db
  build_parquet:
    cmd: Rscript R/build_parquet.R
    deps: 
      - R/build_parquet.R
      - data/chembl_30.db
    outs:
      - data/parquet