stages:
  invalidate:
    cmd: Rscript stages/0_invalidate.R
    outs:
      - staging/checksums.txt
  download_sqlite:
    cmd: Rscript stages/1_build.R
    deps:
      - staging/checksums.txt
    outs:
      - brick/